// import { homePageMockData } from '@root/__mock-props__/component/view/home';
// import { HomePage } from '@src/components/view';
// import { IHomePage } from '@src/types/view';
import axios from 'axios';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';

import { LandingPageView } from '@src/components/view';
import { tableMockData } from '@root/__mock-props__/component';
import { ITableData } from '@src/types/view';
const Home = ({ homePageData }: { homePageData: ITableData }) => {
  return (
    <div>
      <Head>
        <title>TechnoFix Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <LandingPageView {...homePageData} />
      </main>
    </div>
  );
};

export async function getStaticProps() {
  return {
    props: {
      homePageData: tableMockData,
    }, // will be passed to the page component as props
  };
}

export default Home;
